# Generated by Django 5.0.6 on 2024-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write_Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(verbose_name='할 일')),
                ('todo_detail', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
                ('completed', models.BooleanField(verbose_name='완료 여부')),
            ],
        ),
        migrations.DeleteModel(
            name='Write_Diary',
        ),
    ]
