# Generated by Django 5.0.7 on 2024-07-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(verbose_name='게시글 제목')),
                ('post_content', models.TextField(verbose_name='게시글 내용')),
                ('post_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post_writer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='댓글 내용')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('comment_writer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글작성자')),
                ('comment_post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
